
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mawel
 */
public class Field extends javax.swing.JFrame implements PropertyChangeListener{

    protected Mover mover;

    /**
     * Creates new form Field
     */
    public Field() {
        super();
        initComponents();

        mover = new Mover(anim);
        anim.setPaintClient(mover);
        mover.addPropertyChangeListener(this);
    }
    
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        //on hit
        if (evt.getPropertyName().equals("hit")) {
            mover.stop();
            button_ON_OFF.setEnabled(false);
            button_RESET.setEnabled(true);
            if (button_ON_OFF.getText().equals("STOP")) {
                button_ON_OFF.setText("START");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frame = new javax.swing.JPanel();
        ui = new javax.swing.JPanel();
        button_RESET = new javax.swing.JButton();
        button_ON_OFF = new javax.swing.JButton();
        anim = new JMath();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Frame.setLayout(new java.awt.BorderLayout());

        ui.setLayout(new java.awt.GridBagLayout());

        button_RESET.setText("RESET");
        button_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RESETActionPerformed(evt);
            }
        });
        ui.add(button_RESET, new java.awt.GridBagConstraints());

        button_ON_OFF.setText("START");
        button_ON_OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ON_OFFActionPerformed(evt);
            }
        });
        ui.add(button_ON_OFF, new java.awt.GridBagConstraints());

        Frame.add(ui, java.awt.BorderLayout.SOUTH);
        Frame.add(anim, java.awt.BorderLayout.CENTER);

        getContentPane().add(Frame, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_ON_OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ON_OFFActionPerformed
        if (mover.weiter == false) {
            if (button_ON_OFF.getText().equals("START")) {
                button_ON_OFF.setText("STOP");
                button_RESET.setEnabled(false);
            }
            if (mover.data_runner.isEmpty()) {
                mover.init();
            }
            mover.start();
        } else if (mover.weiter == true) {
            mover.stop();
            button_RESET.setEnabled(true);
            if (button_ON_OFF.getText().equals("STOP")) {
                button_ON_OFF.setText("START");
            }
        }
    }//GEN-LAST:event_button_ON_OFFActionPerformed

    private void button_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RESETActionPerformed
        mover.reset();
        button_ON_OFF.setEnabled(true);
    }//GEN-LAST:event_button_RESETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Field.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Field.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Field.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Field.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Field().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Frame;
    private JMath anim;
    private javax.swing.JButton button_ON_OFF;
    private javax.swing.JButton button_RESET;
    private javax.swing.JPanel ui;
    // End of variables declaration//GEN-END:variables
}
